server:
  port: 8088

spring:
  application:
    name: innowise-project

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    clear-checksums: true
    url: jdbc:postgresql://localhost:5432/innowise_db
    user: postgres
    password: password

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info