server:
  port: 8089

# JWT Configuration
jwt:
  secret: "mySuperSecretKeyThatIsVeryLongAndSecure1234567890"
  access-token:
    expiration: 3600000    # 1 hour in milliseconds
  refresh-token:
    expiration: 86400000   # 24 hours in milliseconds

spring:
  application:
    name: authentication-service

  liquibase:
    enabled: false
    default-schema: auth_schema
    liquibase-schema: auth_schema
    change-log: classpath:db/changelog/db.changelog-master.xml
    clear-checksums: true

  datasource:
    url: jdbc:postgresql://postgres:5432/innowise_db?currentSchema=auth_schema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_schema
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

service:
  user:
    url: http://user-service:8088

management:
  endpoints:
    web:
      exposure:
        include: health,info