server:
  port: 8089

# JWT Configuration
jwt:
  secret: ${SECRET_KEY}
  access-token:
    expiration: 3600000    # 1 hour in milliseconds
  refresh-token:
    expiration: 86400000   # 24 hours in milliseconds

spring:
  application:
    name: authentication-service

  liquibase:
    enabled: false
    default-schema: auth_schema
    liquibase-schema: auth_schema
    change-log: classpath:db/changelog/db.changelog-master.xml
    clear-checksums: true

  datasource:
    url: ${USER_SERVICE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_schema
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

service:
  user:
    url: ${USER_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info