server:
  port: 8088

spring:
  application:
    name: user-service

  liquibase:
    enabled: false
    default-schema: user_schema
    liquibase-schema: user_schema
    change-log: classpath:/db/changelog/db.changelog-master.xml
    clear-checksums: true

  datasource:
    url: ${USER_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_schema: user_schema
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis #none
    redis:
      time-to-live: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    redis:
      enabled: false